@include('sections.intro')
@include('sections.personal')
@include('sections.profesores')
@include('sections.agenda')
@include('sections.ubicacion')
@include('sections.proyectos')
@include('sections.blog')
